# Generated by Django 6.0.2 on 2026-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aldiyar', max_length=100, verbose_name='Имя автора')),
                ('role', models.CharField(default='Founder & Lead Developer', max_length=100, verbose_name='Роль/Должность')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='author_avatars/', verbose_name='Фото автора')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на GitHub')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
            ],
            options={
                'verbose_name': 'Информация об авторе',
                'verbose_name_plural': 'Информация об авторе',
            },
        ),
    ]
