# Generated by Django 6.0.2 on 2026-02-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_platformauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL (ссылка)')),
                ('category', models.CharField(default='IT-новости', max_length=50, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Обложка статьи')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Блог (Статьи)',
                'ordering': ['-created_at'],
            },
        ),
    ]
