# Generated by Django 6.0.3 on 2026-03-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_friendship_options_friendship_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='В сети'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Был(а) в сети'),
        ),
    ]
