# Generated by Django 6.0.2 on 2026-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание (например: 18:00 • Онлайн)')),
                ('date', models.DateTimeField(verbose_name='Дата и время события')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочное? (Красный цвет)')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('tag', models.CharField(choices=[('update', 'Обновление'), ('platform', 'Платформа'), ('event', 'Событие')], default='platform', max_length=20, verbose_name='Тэг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
