# Generated by Django 6.0.2 on 2026-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('icon_class', models.CharField(default='fa-solid fa-book', max_length=50, verbose_name='Иконка (FontAwesome)')),
                ('level', models.CharField(choices=[('Easy', 'Easy (Легкий)'), ('Medium', 'Medium (Средний)'), ('Hard', 'Hard (Сложный)')], default='Easy', max_length=10, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
