# Generated by Django 6.0.2 on 2026-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку (желательно 16:9)', null=True, upload_to='course_covers/', verbose_name='Обложка курса'),
        ),
    ]
